### ISSUE TITLE
Using Dividers

### ISSUE THREAD

**Issue by Lucav17** [blzaej/prj-rev-bwfs-dasmoto#2]
In our code we typically want to section our code to make thing more readable. We can do this by wrapping our sections in `<div>` tags, which you could in several times in this code. Look at the highlighted section in the link and then see what I mean:

[https://github.com/blzaej/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's/index.html#L10-L13](url)

**Comment by blzaej** [comment]
OK, thanks div's added
